apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: hipster-grpc
  namespace: istio-system
spec:
  workloadLabels:
    transcode: http
  filters:
  - listenerMatch:            
      listenerType: SIDECAR_INBOUND
    filterName: envoy.grpc_json_transcoder
    filterType: HTTP
    filterConfig:
      proto_descriptor: "/gce/api_descriptor.pb"
      match_incoming_request_route: true
      services: 
        - hipstershop.RecommendationService
        - hipstershop.CurrencyService
        - hipstershop.AdService
        - hipstershop.ProductCatalogService
        - hipstershop.CartService
        - hipstershop.ShippingService
        - hipstershop.PaymentService
        - hipstershop.EmailService
        - hipstershop.CheckoutService

